#!/usr/local/bin/Rscript

#' @importFrom magrittr "%>%"
NULL
#' @import data.table
NULL


#' @export
build_ddl = function(data_entity, data_field, data_model_dir) {
  get_den_pk = function(den, dfl) {
    dfl_pk = dfl %>%
      dplyr::filter(pk_fk == "PK") %>%
      dplyr::select(-pk_fk) %>%
      dplyr::select(fk_pk_data_field_id = data_field_id, fk_data_entity_id = data_entity_id, fk_pk_data_field_name = data_field_name)
    den %>%
      dplyr::select(fk_data_entity_id = data_entity_id, entity_name) %>%
      dplyr::left_join( dfl_pk, by = "fk_data_entity_id") 
  }
  get_dfl_fk = function(den, dfl) {
    dfl_fk = dfl %>%
      dplyr::filter(pk_fk == "FK") %>%
      dplyr::select(-pk_fk) %>%
      dplyr::mutate(fk_data_entity_name = stringr::str_sub(data_field_name, end = -4)) %>%
      dplyr::left_join(get_den_pk(den, dfl), by = c("fk_data_entity_name" = "entity_name"))
  }
  den = data_entity 
  dfl = data_field %>%
    dplyr::inner_join(den, by = "data_entity_id")
  den_pk = get_den_pk(den, dfl)
  sql = data.table::data.table(
                               data_entity_id = den$data_entity_id,
                               sql_create_table = ""
                               ) %>%
    data.table::setkey(data_entity_id)
  ids = dplyr::distinct(dfl, data_entity_id)$data_entity_id
  for (deid in ids) {
    fd = dplyr::filter(dfl, data_entity_id == deid) %>%
      dplyr::left_join(den, by = "data_entity_id")
    table_name = unique(fd$entity_name)
    nonpks = dplyr::filter(fd, pk_fk != "PK")
    pks = dplyr::filter(fd, pk_fk == "PK")
    fks = dplyr::filter(fd, pk_fk == "FK") %>%
      dplyr::left_join(den_pk, by = "data_entity_id")
    sql[deid]$sql_create_table = create_table_sql_template( 
      table_name, nonpks$data_field_name, nonpks$type, pks$data_field_name, fks )
  }
  return(sql)
}

#' @export
create_table_sql_template = function( table_name, columns, types, pks, fks ) {
	# usage:
	# template = create_table_sql_template( "t_c_bonitet_bali", names(cbb) )
	# example output:
  # "CREATE TABLE Vehicle ( vehicle_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, vehicle_type TEXT)"
  template_pk = "%s BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
  sql_pk = sprintf(template_pk, pks)
  template_fk = "%s int REFERENCES %s (%s)"
  sql_fk = sprintf(template_fk, fks$data_field_name, fks$pk_data_entity_name, fks$pk_data_field_name)
  template_nonkey = "%s %s"
  sql_nonkey = sprintf(template_column, columns, types)
  column_sql = c(sql_pk, sql_fk, sql_nonkey)
	column_names = column_sql %>% paste(collapse=",")
	template = "CREATE TABLE %s (%s);"
	result = sprintf( template, table_name, column_names)
	return(result)
}

study_create_table_sql_template = function() {
  table_name = "Vehicle"
  columns = c("vehicle_id", "vehicle_type")
	template = "    CREATE TABLE %s (%s);"
	column_names = columns %>% paste(collapse=",")
	result = sprintf( template, table_name, column_names)

  library(magrittr)
  table_name = "Vehicle"
  columns = c("vehicle_id", "vehicle_type")
  types = c("BIGINT", "TEXT")
	template = "    CREATE TABLE %s (%s);"
  template_column = "%s %s"
  column_sql = sprintf(template_column, columns, types)
  column_sql
	column_names = column_sql %>% paste(collapse=",")
	sprintf( template, table_name, column_names)

  library(magrittr)
  table_name = "Vehicle"
  columns = c("vehicle_type")
  types = c("TEXT")
	template = "    CREATE TABLE %s (%s);"
  pks = c("vehicle_id")
  template_pk = "%s BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
  pk_sql = sprintf(template_pk, pks)
  pk_sql
  template_column = "%s %s"
  column_sql = sprintf(template_column, columns, types)
  column_sql = c(pk_sql, column_sql)
  column_sql
	column_names = column_sql %>% paste(collapse=",")
	sprintf( template, table_name, column_names)
}

