#!/usr/local/bin/Rscript

#' @importFrom magrittr "%>%"
NULL


build_ddl = function(data_entity, data_field, data_model_dir) {
  den = data_entity %>%
    data.table::setkey(data_entity_id)
  dfl = data_field %>%
    dplyr::inner_join(den, by = "data_entity_aid")
  sql = data.table::data.table(
                               data_entity_aid = den$data_entity_aid,
                               sql_create_table = ""
                               ) %>%
    data.table::setkey(data_entity_aid)
  ids = dplyr::distinct(dfl, data_entity_aid)$data_entity_aid
  deid = ids[1]
  for (deid in ids) {
    fd = dplyr::filter(dfl, data_entity_aid == deid)
    table_name = unique(fd$entity_name)
    nonpks = dplyr::filter(fd, pk_fk != "PK")
    pks = dplyr::filter(fd, pk_fk == "PK")
    sql[deid]$sql_create_table = create_table_sql_template( 
      table_name, nonpks$data_field_name, nonpks$type, pks$data_field_name )
    den2 = den %>%
      mutate(sql_create_table = create_table_sql_template( table_name, columns, types, pks$data_field_name ))
  }
  lapply(den$entity_name)
  create_table_sql_template()
}

create_table_sql_template = function( table_name, columns, types, pks ) {
	# usage:
	# template = create_table_sql_template( "t_c_bonitet_bali", names(cbb) )
	# example output:
  # "CREATE TABLE Vehicle ( vehicle_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, vehicle_type TEXT)"
	# [1] "INSERT INTO T_Kesim_Noktasi (id,eroziya_enum_id,qranulometrik_terkib_enum_id,soraketlesme_derecesi_enum_id,sorlasma_enum_id) VALUES (%s,%s,%s,%s,%s);"
  template_pk = "%s BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
  pk_sql = sprintf(template_pk, pks)
  template_column = "%s %s"
  column_sql = pk_sql %>%
    c( sprintf(template_column, columns, types) )
	column_names = column_sql %>% paste(collapse=",")
	template = "CREATE TABLE %s (%s);"
	result = sprintf( template, table_name, column_names)
	return(result)
}

study_create_table_sql_template = function() {
  table_name = "Vehicle"
  columns = c("vehicle_id", "vehicle_type")
	template = "    CREATE TABLE %s (%s);"
	column_names = columns %>% paste(collapse=",")
	result = sprintf( template, table_name, column_names)

  library(magrittr)
  table_name = "Vehicle"
  columns = c("vehicle_id", "vehicle_type")
  types = c("BIGINT", "TEXT")
	template = "    CREATE TABLE %s (%s);"
  template_column = "%s %s"
  column_sql = sprintf(template_column, columns, types)
  column_sql
	column_names = column_sql %>% paste(collapse=",")
	sprintf( template, table_name, column_names)

  library(magrittr)
  table_name = "Vehicle"
  columns = c("vehicle_type")
  types = c("TEXT")
	template = "    CREATE TABLE %s (%s);"
  pks = c("vehicle_id")
  template_pk = "%s BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
  pk_sql = sprintf(template_pk, pks)
  pk_sql
  template_column = "%s %s"
  column_sql = sprintf(template_column, columns, types)
  column_sql = c(pk_sql, column_sql)
  column_sql
	column_names = column_sql %>% paste(collapse=",")
	sprintf( template, table_name, column_names)
}

